# -*- coding: utf-8 -*-
"""enet_tensorflow_debug.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-3Fux52CL13e4d6ZrrCE8fX7MPHw5Hvb

## Import Enet github repo
"""

! rm -rf enet_tensorflow && git clone https://github.com/gevero/enet_tensorflow.git

"""## Libraries"""

# numpy
import numpy as np

# enet
import sys
sys.path.append('./enet_tensorflow')
import layers

# tensorflow
import tensorflow as tf
tf.enable_eager_execution()

m_torch = np.array([[[[ 1.,  2.,  3.,  9.],
                            [ 5,  6.1,  7.,  8.],
                            [ 9, 10, 11, 12],
                            [13, 14, 15, 16]]]])
m_tf = np.swapaxes(m_torch,1,2).copy()
m_tf = np.swapaxes(m_tf,2,3)
m_tf = tf.cast(m_tf, tf.float32)

m_tf.shape

"""## Create dummy tensor and try to apply bottleneck module"""

BNtest = layers.BottleNeck(output_filters = 4, kernel_strides=(1,1),downsample=True)

output_tf, argmax_tf, input_tf = BNtest(m_tf)

BDtest = layers.BottleDeck(output_filters=1)

BDtest(output_tf,input_tf, argmax_tf)

